feat(user): convert language into an array
shoonyatech/shoonya.freelance.graphql pull request #8
Opened 2021-09-22 19:20 UTC by hussamkhatib

2021-09-23 05:19 UTC, souvikbasu requested changes

2021-09-23 05:19 UTC, souvikbasu commented on models.js
>    language : {
rename to languages

2021-09-24 09:09 UTC, hussamkhatib commented on models.js
>    language : {
Resolved now

2021-09-26 18:16 UTC, souvikbasu approved these changes

2021-09-26 18:16 UTC, merged